name: My First Workflow

on:
  push: 

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: My name
        run: echo "Anuj Nahar"

      - name: Goal
        run: echo "I am learning CI/CD"

      - name: Current Directory
        run: pwd
