name: Python CI

on: 
  push:
  pull_request: 

env:
  APP_NAME: github-actions-learning

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      test-status: ${{ steps.test-status.outputs.status }}

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set Up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Display python version
        run: python --version

      - name: Python setup status
        if: ${{ success() }}
        run: echo "Python Setup is Successfully implemented"

      - name: Show application name
        run: echo "Application --> $APP_NAME"

      - name: Show branch name
        run: echo "Branch -> ${{ github.ref_name }}"

      - name: Show application environment
        run: echo "Environment -> ${{ vars.APP_ENV }}"

      - name: Use Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

        run: |
            if [ -n "$MY_SECRET" ]; then
              echo "Secret is configured"
            else
              echo "Secret is missing"
            fi
            
      # - name: Simulate failure
      #   run: exit 1

      - name: failure handler
        if: ${{ failure() }} 
        run: echo "A previous step failed"
        
      - name: Create Report
        run: |
          echo "CI Pipeline Report" > report-${{ matrix.python-version }}.txt
          echo "Application: $APP_NAME" >> report-${{ matrix.python-version }}.txt
          echo "Branch: ${{ github.ref_name }}" >> report-${{ matrix.python-version }}.txt
          echo "Python version: " >> report-${{ matrix.python-version }}.txt
          python --version >> report-${{ matrix.python-version }}.txt

      - name: Upload report
        uses: actions/upload-artifact@v7
        with:
          name: ci-report-python-${{ matrix.python-version }}
          path: report-${{ matrix.python-version }}.txt
          
      - name: Run python program
        run: python hello.py

      - name: Generate test status
        id: test-status
        run: echo "status=passed" >> "$GITHUB_OUTPUT"

  build:
    needs: test
    if: needs.test.outputs.test-status == 'passed'
    runs-on: ubuntu-latest

    steps:
      - name: Download report
        uses: actions/download-artifact@v8
        with:
          pattern: ci-report-python-*
          path: reports
          merge-multiple: true

      - name: Show report
        run: |
            echo "Downloaded reports: "
            ls -la reports
            echo ""
            for file in reports/*;do
              echo "======$file======"
              cat $file
              echo ""
            done
        
      - name: Start status
        run: echo "Build Started"

      - name: Complete status
        run: echo "Build Completed"

      - name: Show test status
        run: echo "Test status --> ${{ needs.test.outputs.test-status }}"
        
  deploy:
    needs: build
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    
    steps:
      - name: deploying application
        run: echo "Deploying...."
        
