name: Python CI

on: 
  push:
  pull_request: 

env:
  APP_NAME: github-actions-learning

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set Up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Display python version
        run: python --version

      - name: Show application name
        run: echo "Application --> $APP_NAME"

      - name: Show branch name
        run: echo "Branch -> ${{ github.ref_name }}"

      - name: Show application environment
        run: echo "Environment -> ${{ vars.APP_ENV }}"

      - name: Use Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

        run: |
            if [ -n "$MY_SECRET" ]; then
              echo "Secret is configured"
            else
              echo "Secret is missing"
            fi
            
      # - name: Simulate failure
      #   run: exit 1

      - name: failure handler
        if: ${{ failure() }} 
        run: echo "A previous step failed"
        
      - name: Create Report
        run: |
          echo "CI Pipeline Report" > report.txt
          echo "Application: $APP_NAME" >> report.txt
          echo "Branch: ${{ github.ref_name }}" >> report.txt
          echo "Python version: " >> report.txt
          python --version >> report.txt

      - name: Upload report
        uses: actions/upload-artifact@v7
        with:
          name: ci-report
          path: report.txt
          
      - name: Run python program
        run: python hello.py

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download report
        uses: actions/download-artifact@v8
        with:
          name: ci-report

      - name: Show report
        run: cat report.txt
        
      - name: Start status
        run: echo "Build Started"

      - name: Complete status
        run: echo "Build Completed"

  deploy:
    needs: build
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    
    steps:
      - name: deploying application
        run: echo "Deploying...."
        
