name: Reusable Python Workflow

on:
  workflow_call: 
    inputs:
      python-version:
        description: Python version to use
        required: true
        type: string

jobs:
  python-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ inputs.python-version }}

      - name: Display python version
        run: python --version

      - name: Run python program
        run: python hello.py
