name: Variables and Secret Configurations

on: 
  push: 
  pull_request: 

env:
  MY_Secret: ${{secrets.MY_SECRET}}

jobs:
  config:
    runs-on: ubuntu-latest
  
    steps:
      - name: Display Application Environment
        run: echo "Environment -> ${{ vars.APP_ENV }}"
        
      - name: Show Secrets
        run:  |
            if [ -n "$MY_Secret"];then
              echo "Secret is configured"
            else
              echo "Secret is missing"
            fi 
            
